package br.com.vah.protocolo.constants;

public enum TipoDocumentoEnum {
  PRESCRICAO("Prescrição"),
  DOCUMENTO_PRONTUARIO("Prontuário"),
  EVOLUCAO("Evolução"),
  FOLHA_ANESTESICA("Folha Anestésica"),
  DESCRICAO_CIRURGICA("Descrição Cirúrgica"),
  REGISTRO_DOCUMENTO("Registro Documento"),
  PROTOCOLO("Protocolo"),
  EVOLUCAO_ENFERMAGEM("Evolução/Anotação"),
  DOC_MANUAL_EVOLUCAO("Evolução"),
  DOC_MANUAL_PRESCRICAO("Prescrição"),
  DOC_MANUAL_EVOLUCAO_ANOTACAO("Evolução"),
  DOC_MANUAL_DESCRICAO_CIRURGICA("Descrição Cirurgica"),
  DOC_MANUAL_FOLHA_ANESTESICA("Folha Anestésica"),
  DOC_MANUAL_HDA("HDA"),
  DOC_MANUAL_EVOLUCAO_ENFERMAGEM("Evolução/Anotação"),
  DOC_MANUAL_EXAME_FISICO_EVOLUCAO_ENFERMAGEM("Exame Físico e Evolução de Enfermagem"),
  DOC_MANUAL_REGISTRO_SINAIS_VITAIS_PS("Registro de Sinais Vitais - PS"),
  DOC_MANUAL_CLASSIFICACAO_RISCO("Classificação de Risco"),
  DOC_MANUAL_FOLHA_CLASSIFICACAO("Folha de Classificação"),
  DOC_MANUAL_SADT("SADT"),
  DOC_MANUAL_AUTORIZACAO_PS("Autorização (PS)"),
  HDA("HDA"),
  CLASSIFICACAO_DE_RISCO("Class. de Risco"),
  DIAGNOSTICO_DO_ATENDIMENTO("Diag. do Atend."),
  GUIA_SADT("SADT"),
  ATENDIMENTO("Atendimento"),
  DOC_MANUAL_NEBULIZACAO("Nebulização"),
  DOC_MANUAL_SUTURA("Sutura"),
  DOC_MANUAL_ELETROCARDIOGRAMA("Eletrocardiograma"),
  DOC_MANUAL_DRENAGEM_DE_ABCESSO("Drenagem de Abcesso"),
  DOC_MANUAL_IMOBILIZACAO("Imobilização"),
  DOC_MANUAL_CANTOPLASTIA("Cantoplastia"),
  DOC_MANUAL_DESBRIDAMENTO("Desbridamento"),
  DOC_MANUAL_EXERESSE("Exeresse"),
  DOC_MANUAL_PARACENTESE("Paracentese"),
  DOC_MANUAL_PUNCAO_LOMBAR("Punção Lombar"),
  DOC_MANUAL_RETIRADA_DE_CORPO_ESTRANHO("Retirada de Corpo Estranho"),
  DOC_MANUAL_TORACOSTOMIA("Toracostomia"),
  DOC_MANUAL_PROTOCOLO_DOR_TORACICA("Protocolo de dor Torácica"),
  DOC_MANUAL_FORMULARIO_DE_VITIMAS("Formulário de Vitaminas"),
  DOC_MANUAL_PROTOCOLO_DE_AVC("Protocolo de AVC"),
  DOC_MANUAL_AUTORIZACAO("Autorização"),
  DOC_MANUAL_JUSTIFICATIVA_DE_MEDICACAO("Justificativa de Medicação"),
  DOC_MANUAL_PARECER("Parecer"),
  DOC_MANUAL_CONSULTA("Consulta"),
  DOC_MANUAL_LACRE_DE_MATERIAL("Lacre de Material"),
  DOC_MANUAL_GUIA_SOLICITACAO_DE_INTERNACAO("Guia de Solicitação de Internação"),
  DOC_MANUAL_PRESCRICAO_MANUAL("Prescrição Manual"),
  DOC_MANUAL_FORMULARIO_DE_PASSAGEM_DE_SONDA("Formulário de Passagem de Sonda"),
  DOC_MANUAL_CURATIVO("Curativo"),
  DOC_MANUAL_PARECER_PEDIATRIA("Parecer Pediatria"),
  DOC_MANUAL_PARECER_ORTOPEDIA("Parecer Ortopedia"),
  DOC_MANUAL_PARECER_CIRURGIA_GERAL("Parecer Cirurgia Geral"),
  DOC_MANUAL_PARECER_CLINICA_MEDICA("Parecer Clínica Médica"),
  DOC_MANUAL_HISTORICO_DE_ENFERMAGEM("Histórico de Enfermagem"),
  DOC_MANUAL_PARECER_OUTRAS_ESPECIALIDADES("Parecer de Outras Especialidades"),
  DOC_MANUAL_SOLICITACAO_DE_INTERNACAO_SUS("Solicitação de Internação SUS"),
  DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_AVC("Protocolo de AVC"),
  DOC_MANUAL_REGISTRO_DE_MONITORIZACAO_DE_SINAIS("Registrode Monitorização de Sinais"),
  DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_SEPSE("Protocolo de SEPSE"),
  DOC_MANUAL_REGISTRO_DE_SOLICITACAO_DE_INTERNACAO("Registro de Solicitação de Internação"),
  DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_DE_COLICA_RENAL("Protocolo de Cólica Renal"),
  DOC_MANUAL_FORMULARIO_DE_REPOSICAO_DO_CARRO_DE_EMERGENCIA("Reposição do Carro de Emergência"),
  DOC_MANUAL_RELATORIO_DE_CONSUMO_CENTRO_CIRURGICO("Relatório de Consumo Centro Cirúrgico"),
  DOC_MANUAL_TERMO_DE_ESCLARECIMENTO_TRANSFUSAO_DE_SANGUE("Termo de Esclarecimento Transfusão de Sangue"),
  DOC_MANUAL_CATETER_VENOSO("Cateter Venoso"),
  DOC_MANUAL_CLASSIFICACAO_DE_RISCO("Classificação de Risco"),
  DOC_MANUAL_PUNCAO_VENOSA_PROFUNDA("Punção Venosa Profunda"),
  DOC_MANUAL_TERMO_DE_ESCLARECIMENTO_E_CONSENTIMENTO_PARA_TRANSFUSAO("Termo de Esclarecimento e Consentimento para Transfusão"),
  DOC_MANUAL_TERMO_DE_AUTORIZACAO_DE_DOACAO_DE_ORGAO("Termo de Autorização de Doação de Órgão"),
  DOC_MANUAL_HISTORIA_MEDICA_E_SOCIAL_DO_DOADOR_DE_TECIDOS("História Médica e Social do Doador de Tecidos"),
  DOC_MANUAL_FICHA_DE_NOTIFICACAO_DE_OBITO("Ficha de Notificação de Óbito"),
  DOC_MANUAL_PROTOCOLO_DE_ENCAMINHAMENTO_DE_CORPOS_AO_SERVICO_DE_VERIFICACAO_DE_OBITOS("Protocolo de Encaminhamento de Corpos ao Serviço de Verificação de Óbitos"),
  DOC_MANUAL_DECLARACAO_DE_OBITO("Declaração de Óbito"),
  DOC_MANUAL_PUNCAO_ARTICULAR("Punção Articular");


  private String label;

  TipoDocumentoEnum(String label) {
    this.label = label;
  }

  public String getLabel() {
    return this.label;
  }

  public static TipoDocumentoEnum getByTitle(String title) {
    switch (title) {
      case "Documento de Prontuário":
        return DOCUMENTO_PRONTUARIO;
      case "Evolução/Anotação":
        return EVOLUCAO_ENFERMAGEM;
      case "Prescrição":
        return PRESCRICAO;
      case "Evolução":
        return EVOLUCAO;
      case "Descrição Cirurgica":
        return DESCRICAO_CIRURGICA;
      case "Folha Anestésica":
        return FOLHA_ANESTESICA;
      default:
        return null;
    }
  }

  public static TipoDocumentoEnum[] documentosManuais = {
      DOC_MANUAL_EVOLUCAO,
      DOC_MANUAL_PRESCRICAO,
      DOC_MANUAL_EVOLUCAO_ANOTACAO,
      DOC_MANUAL_DESCRICAO_CIRURGICA,
      DOC_MANUAL_FOLHA_ANESTESICA,
      DOC_MANUAL_HDA,
      DOC_MANUAL_EVOLUCAO_ENFERMAGEM,
      DOC_MANUAL_EXAME_FISICO_EVOLUCAO_ENFERMAGEM,
      DOC_MANUAL_REGISTRO_SINAIS_VITAIS_PS,
      DOC_MANUAL_CLASSIFICACAO_RISCO,
      DOC_MANUAL_FOLHA_CLASSIFICACAO,
      DOC_MANUAL_SADT,
      DOC_MANUAL_AUTORIZACAO_PS,
      DOC_MANUAL_NEBULIZACAO,
      DOC_MANUAL_SUTURA,
      DOC_MANUAL_ELETROCARDIOGRAMA,
      DOC_MANUAL_DRENAGEM_DE_ABCESSO,
      DOC_MANUAL_IMOBILIZACAO,
      DOC_MANUAL_CANTOPLASTIA,
      DOC_MANUAL_DESBRIDAMENTO,
      DOC_MANUAL_EXERESSE,
      DOC_MANUAL_PARACENTESE,
      DOC_MANUAL_PUNCAO_LOMBAR,
      DOC_MANUAL_RETIRADA_DE_CORPO_ESTRANHO,
      DOC_MANUAL_TORACOSTOMIA,
      DOC_MANUAL_PROTOCOLO_DOR_TORACICA,
      DOC_MANUAL_FORMULARIO_DE_VITIMAS,
      DOC_MANUAL_PROTOCOLO_DE_AVC,
      DOC_MANUAL_AUTORIZACAO,
      DOC_MANUAL_JUSTIFICATIVA_DE_MEDICACAO,
      DOC_MANUAL_PARECER,
      DOC_MANUAL_CONSULTA,
      DOC_MANUAL_LACRE_DE_MATERIAL,
      DOC_MANUAL_GUIA_SOLICITACAO_DE_INTERNACAO,
      DOC_MANUAL_PRESCRICAO_MANUAL,
      DOC_MANUAL_FORMULARIO_DE_PASSAGEM_DE_SONDA,
      DOC_MANUAL_CURATIVO,
      DOC_MANUAL_PARECER_PEDIATRIA,
      DOC_MANUAL_PARECER_ORTOPEDIA,
      DOC_MANUAL_PARECER_CIRURGIA_GERAL,
      DOC_MANUAL_PARECER_CLINICA_MEDICA,
      DOC_MANUAL_HISTORICO_DE_ENFERMAGEM,
      DOC_MANUAL_PARECER_OUTRAS_ESPECIALIDADES,
      DOC_MANUAL_SOLICITACAO_DE_INTERNACAO_SUS,
      DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_AVC,
      DOC_MANUAL_REGISTRO_DE_MONITORIZACAO_DE_SINAIS,
      DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_SEPSE,
      DOC_MANUAL_REGISTRO_DE_SOLICITACAO_DE_INTERNACAO,
      DOC_MANUAL_FORMULARIO_DE_PROTOCOLO_DE_COLICA_RENAL,
      DOC_MANUAL_FORMULARIO_DE_REPOSICAO_DO_CARRO_DE_EMERGENCIA,
      DOC_MANUAL_RELATORIO_DE_CONSUMO_CENTRO_CIRURGICO,
      DOC_MANUAL_TERMO_DE_ESCLARECIMENTO_TRANSFUSAO_DE_SANGUE,
      DOC_MANUAL_CATETER_VENOSO,
      DOC_MANUAL_CLASSIFICACAO_DE_RISCO,
      DOC_MANUAL_PUNCAO_VENOSA_PROFUNDA,
      DOC_MANUAL_TERMO_DE_ESCLARECIMENTO_E_CONSENTIMENTO_PARA_TRANSFUSAO,
      DOC_MANUAL_TERMO_DE_AUTORIZACAO_DE_DOACAO_DE_ORGAO,
      DOC_MANUAL_HISTORIA_MEDICA_E_SOCIAL_DO_DOADOR_DE_TECIDOS,
      DOC_MANUAL_FICHA_DE_NOTIFICACAO_DE_OBITO,
      DOC_MANUAL_PROTOCOLO_DE_ENCAMINHAMENTO_DE_CORPOS_AO_SERVICO_DE_VERIFICACAO_DE_OBITOS,
      DOC_MANUAL_DECLARACAO_DE_OBITO,
      DOC_MANUAL_PUNCAO_ARTICULAR
  };

  public Boolean isDocManual() {
    for (int i = 0, len = documentosManuais.length; i < len; i++) {
      if (this.equals(documentosManuais[i])) {
        return true;
      }
    }
    return false;
  }

}
