-- DDL SISTEMA NOVO PROTOCOLO

-- SETOR

CREATE TABLE USRDBVAH.TB_NPTC_SETOR
( CD_SETOR NUMBER(*) PRIMARY KEY NOT NULL,
  NM_SETOR VARCHAR2(100),
  CD_NIVEL NUMBER(1),
  CD_SETOR_MV NUMBER(*),
  CONSTRAINT FK_NPTC_SETOR_1 FOREIGN KEY (CD_SETOR_MV) REFERENCES DBAMV.TB_SETOR (CD_SETOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_SETOR;

-- USUÁRIO

CREATE TABLE USRDBVAH.TB_NPTC_USUARIO
( ID NUMBER(*) PRIMARY KEY NOT NULL,
  DS_LOGIN VARCHAR2(75),
  NM_TITULO VARCHAR2(200),
  CD_ROLE NUMBER(1),
  CD_SETOR NUMBER(*),
  CONSTRAINT FK_NPTC_USUARIO_1 FOREIGN KEY (CD_SETOR) REFERENCES USRDBVAH.TB_NPTC_SETOR (CD_SETOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_USUARIO;

-- PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_ATENDIMENTO NUMBER(*),
  CD_STATUS NUMBER(2),
  CD_REG_FAT NUMBER(*),
  CD_SETOR_ORIGEM NUMBER(*),
  CD_SETOR_DESTINO NUMBER(*),
  DT_ENVIO DATE,
  DT_RESPOSTA DATE,
  SN_REENVIADO VARCHAR2(1),
  SN_ARQUIVADO VARCHAR2(1),
  NM_LOCALIZACAO VARCHAR2(100),
  CONSTRAINT FK_NPTC_PROTOCOLO_1 FOREIGN KEY (CD_SETOR_ORIGEM) REFERENCES USRDBVAH.TB_NPTC_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_PROTOCOLO_2 FOREIGN KEY (CD_SETOR_DESTINO) REFERENCES USRDBVAH.TB_NPTC_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_PROTOCOLO_3 FOREIGN KEY (CD_ATENDIMENTO) REFERENCES DBAMV.TB_ATENDIME (CD_ATENDIMENTO),
  CONSTRAINT FK_NPTC_PROTOCOLO_4 FOREIGN KEY (CD_REG_FAT) REFERENCES DBAMV.REG_FAT (CD_REG_FAT)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_PROTOCOLO;

-- DOCUMENTO PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_DOCUMENTO_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_ITEM_PRONTUARIO NUMBER(*) NOT NULL,
  CD_ATENDIMENTO NUMBER(*),
  CD_TIPO NUMBER(2) NOT NULL,
  NM_DESCRICAO VARCHAR(40),
  NM_CONSELHO VARCHAR(30),
  NM_PRESTADOR VARCHAR(40),
  DT_HORA_CRIACAO DATE,
  DT_HORA_IMPRESSAO DATE,
  DT_REFERENCIA DATE
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_DOCUMENTO_PROTOCOLO;
CREATE INDEX USRDBVAH.IDX_NPTC_DOCUMENTO_PROTOCOLO ON USRDBVAH.TB_NPTC_DOCUMENTO_PROTOCOLO (CD_ITEM_PRONTUARIO, CD_TIPO);

CREATE TABLE USRDBVAH.TB_NPTC_CAIXA_ENTRADA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_DOCUMENTO NUMBER(*),
  CD_ATENDIMENTO NUMBER(*),
  CD_REG_FAT NUMBER(*),
  CD_CONVENIO NUMBER(*),
  ID_SETOR_ORIGEM NUMBER(*),
  ID_SETOR_DESTINO NUMBER(*),
  DT_CRIACAO DATE,
  DT_VINCULACAO DATE,
  SN_VINCULADO VARCHAR2(1),
  NM_DESCRICAO VARCHAR2(75),
  CONSTRAINT FK_NPTC_CAIXA_ENTRADA_1 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_CAIXA_ENTRADA_2 FOREIGN KEY (ID_SETOR_ORIGEM) REFERENCES USRDBVAH.TB_NPTC_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_CAIXA_ENTRADA_3 FOREIGN KEY (ID_SETOR_DESTINO) REFERENCES USRDBVAH.TB_NPTC_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_CAIXA_ENTRADA_4 FOREIGN KEY (ID_DOCUMENTO) REFERENCES USRDBVAH.TB_NPTC_DOCUMENTO_PROTOCOLO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_CAIXA_ENTRADA;

-- ITEM  PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_IT_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*) NOT NULL,
  ID_DOCUMENTO NUMBER(*),
  ID_PROTOCOLO_FILHO NUMBER(*),
  ID_CAIXA_ENTRADA NUMBER(*),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_1 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_2 FOREIGN KEY (ID_DOCUMENTO) REFERENCES USRDBVAH.TB_NPTC_DOCUMENTO_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_3 FOREIGN KEY (ID_PROTOCOLO_FILHO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_4 FOREIGN KEY (ID_CAIXA_ENTRADA) REFERENCES USRDBVAH.TB_NPTC_CAIXA_ENTRADA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_IT_PROTOCOLO;

-- HISTÓRICO

CREATE TABLE USRDBVAH.TB_NPTC_HISTORICO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  ID_SETOR_ORIGEM NUMBER(*),
  ID_SETOR_DESTINO NUMBER(*),
  DT_ALTERACAO DATE,
  CD_ACAO NUMBER(1),
  CONSTRAINT FK_NPTC_HISTORICO_1 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_HISTORICO_2 FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_HISTORICO;

-- COMENTARIO

CREATE TABLE USRDBVAH.TB_NPTC_COMENTARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  DT_CRIACAO DATE,
  NM_COMENTARIO VARCHAR2(255),
  CONSTRAINT FK_NPTC_COMENTARIO_1 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_COMENTARIO_2 FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_COMENTARIO;

-- TABELAS DO SAME

CREATE TABLE USRDBVAH.TB_NPTC_SALA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  NM_TITULO VARCHAR2(100),
  DT_CRIACAO DATE
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_SALA;

-- ARMARIO

CREATE TABLE USRDBVAH.TB_NPTC_ARMARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_SALA NUMBER(*),
  VL_COLUNAS NUMBER(*),
  VL_LINHAS NUMBER(*),
  DT_CRIACAO DATE,
  NM_TITULO VARCHAR2(100),
  CONSTRAINT FK_NPTC_ARMARIO_1 FOREIGN KEY (ID_SALA) REFERENCES USRDBVAH.TB_NPTC_SALA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_ARMARIO;

-- ITEM ARMÁRIO

CREATE TABLE USRDBVAH.TB_NPTC_ITEM_ARMARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_ARMARIO NUMBER(*),
  ID_PROTOCOLO NUMBER(*),
  NM_LINHA VARCHAR(3),
  NM_COLUNA VARCHAR(3),
  DT_CRIACAO DATE,
  CONSTRAINT FK_NPTC_ITEM_ARMARIO_1 FOREIGN KEY (ID_ARMARIO) REFERENCES USRDBVAH.TB_NPTC_ARMARIO (ID),
  CONSTRAINT FK_NPTC_ITEM_ARMARIO_2 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_ITEM_ARMARIO;

-- CAIXA

CREATE TABLE USRDBVAH.TB_NPTC_CAIXA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_SALA NUMBER(*),
  DT_CRIACAO DATE,
  NM_TITULO VARCHAR2(100),
  CONSTRAINT FK_NPTC_CAIXA_1 FOREIGN KEY (ID_SALA) REFERENCES USRDBVAH.TB_NPTC_SALA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_CAIXA;

-- ENVELOPE

CREATE TABLE USRDBVAH.TB_NPTC_ENVELOPE
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_CAIXA NUMBER(*),
  DT_CRIACAO DATE,
  NM_TITULO VARCHAR2(100),
  CONSTRAINT FK_NPTC_ENVELOPE_1 FOREIGN KEY (ID_CAIXA) REFERENCES USRDBVAH.TB_NPTC_CAIXA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_ENVELOPE;

-- ENVELOPE x PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_PROTOCOLO_ENVELOPE
(
  ID_ENVELOPE NUMBER(*),
  ID_PROTOCOLO NUMBER(*),
  CONSTRAINT PK_NPTC_PROTCOLO_ENVELOPE PRIMARY KEY (ID_ENVELOPE, ID_PROTOCOLO),
  CONSTRAINT FK_NPTC_PROTOCOLO_ENVELOPE_1 FOREIGN KEY (ID_ENVELOPE) REFERENCES USRDBVAH.TB_NPTC_ENVELOPE (ID),
  CONSTRAINT FK_NPTC_PROTOCOLO_ENVELOPE_2 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID)
);

INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(1, 'SECRETARIA CORA CORALINA', 0, 44);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(2, 'SECRETARIA RUBEM BRAGA', 0, 45);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(3, 'SECRETARIA AUGUSTO RUSCHI', 0, 42);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(4, 'SECRETARIA MONTEIRO LOBATO', 0, 43);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(5, 'SECRETARIA HOMERO MASSENA', 0, 41);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(6, 'SECRETARIA UTI GERAL I', 0, 31);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(7, 'SECRETARIA UTI GERAL II', 0, 32);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(8, 'FATURAMENTO CENTRAL', 1, NULL);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(9, 'ENVIOS', 2, NULL);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(10, 'AUDITORIA', 3, NULL);
INSERT INTO USRDBVAH.TB_NPTC_SETOR (CD_SETOR, NM_SETOR, CD_NIVEL, CD_SETOR_MV) VALUES(11, 'SAME', 4, NULL);

-- CLEAR DATABASE

DROP TABLE USRDBVAH.TB_NPTC_SALA;
DROP TABLE USRDBVAH.TB_NPTC_ARMARIO;
DROP TABLE USRDBVAH.TB_NPTC_ITEM_ARMARIO;
DROP TABLE USRDBVAH.TB_NPTC_CAIXA;
DROP TABLE USRDBVAH.TB_NPTC_ENVELOPE;
DROP TABLE USRDBVAH.TB_NPTC_PROTOCOLO_ENVELOPE;
DROP TABLE USRDBVAH.TB_NPTC_COMENTARIO;
DROP TABLE USRDBVAH.TB_NPTC_HISTORICO;
DROP TABLE USRDBVAH.TB_NPTC_IT_PROTOCOLO;
DROP TABLE USRDBVAH.TB_NPTC_CAIXA_ENTRADA;
DROP TABLE USRDBVAH.TB_NPTC_DOCUMENTO_PROTOCOLO;
DROP TABLE USRDBVAH.TB_NPTC_PROTOCOLO;
DROP TABLE USRDBVAH.TB_NPTC_USUARIO;
DROP TABLE USRDBVAH.TB_NPTC_SETOR;

DROP SEQUENCE USRDBVAH.SEQ_NPTC_COMENTARIO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_HISTORICO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_CAIXA_ENTRADA;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_PROTOCOLO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_DOCUMENTO_PROTOCOLO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_IT_PROTOCOLO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_USUARIO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_SETOR;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_SALA;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_ARMARIO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_ITEM_ARMARIO;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_CAIXA;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_ENVELOPE;
DROP SEQUENCE USRDBVAH.SEQ_NPTC_PROTOCOLO_ENVELOPE;


