-- DDL SISTEMA NOVO PROTOCOLO

-- PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_ATENDIMENTO NUMBER(*),
  CD_REG_FAT NUMBER(*),
  CD_STATUS NUMBER(1),
  CD_SETOR_ORIGEM NUMBER(*),
  CD_SETOR_DESTINO NUMBER(*),
  DT_ENVIO DATE,
  DT_RESPOSTA DATE,
  SN_REENVIADO VARCHAR2(1),
  SN_ARQUIVADO VARCHAR2(1),
  CONSTRAINT FK_NPTC_SETOR_ORIGEM FOREIGN KEY (CD_SETOR_ORIGEM) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_SETOR_DESTINO FOREIGN KEY (CD_SETOR_DESTINO) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_ANTEDIME FOREIGN KEY (CD_ATENDIMENTO) REFERENCES DBAMV.TB_ATENDIME (CD_ATENDIMENTO),
  CONSTRAINT FK_NPTC_REG_FAT FOREIGN KEY (CD_REG_FAT) REFERENCES DBAMV.REG_FAT (CD_REG_FAT)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_PROTOCOLO;

-- ITEM  PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_IT_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*) NOT NULL,
  CD_PRE_MED NUMBER(*),
  CD_AVISO_CIRURGIA NUMBER(*),
  CD_REGISTRO_DOCUMENTO NUMBER(*),
  ID_DOC_MANUAL NUMBER(*),
  ID_PROTOCOLO_REENVIO NUMBER(*),
  CD_TIPO VARCHAR2(50),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK1 FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK2 FOREIGN KEY (CD_PRE_MED) REFERENCES DBAMV.PRE_MED (CD_PRE_MED),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK3 FOREIGN KEY (CD_AVISO_CIRURGIA) REFERENCES DBAMV.TB_AVISO_CIRURGIA (CD_AVISO_CIRURGIA),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK4 FOREIGN KEY (CD_REGISTRO_DOCUMENTO) REFERENCES DBAMV.REGISTRO_DOCUMENTO (CD_REGISTRO_DOCUMENTO),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK5 FOREIGN KEY (ID_DOC_MANUAL) REFERENCES USRDBVAH.TB_NPTC_DOC_MANUAL (ID),
  CONSTRAINT FK_NPTC_IT_PROTOCOLO_FK6 FOREIGN KEY (ID_PROTOCOLO_REENVIO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_IT_PROTOCOLO;

-- DOCUMENTO MANUAL

CREATE TABLE USRDBVAH.TB_NPTC_DOC_MANUAL
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_CODIGO NUMBER(*),
  CD_TIPO NUMBER(2),
  NM_OBSERVACAO VARCHAR(50),
  CD_PRESTADOR NUMBER(*),
  DH_CRIACAO DATE,
  DH_IMPRESSAO DATE,
  CONSTRAINT FK_NPTC_DOC_MAN_PREST FOREIGN KEY (CD_PRESTADOR) REFERENCES DBAMV.PRESTADOR (CD_PRESTADOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_DOC_MANUAL;

-- HISTÓRICO

CREATE TABLE USRDBVAH.TB_NPTC_HISTORICO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  DT_ALTERACAO DATE,
  CD_STATUS NUMBER(1),
  CONSTRAINT FK_NPTC_HIST_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_HIST_USER FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_HISTORICO;

-- COMENTARIO

CREATE TABLE USRDBVAH.TB_NPTC_COMENTARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  DT_CRIACAO DATE,
  NM_COMENTARIO VARCHAR2(255),
  CONSTRAINT FK_NPTC_COMEN_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_COMEN_USER FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_COMENTARIO;