-- DDL SISTEMA NOVO PROTOCOLO

-- PROTOCOLO

CREATE TABLE USRDBVAH.TB_NPTC_PROTOCOLO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_ATENDIMENTO NUMBER(*),
  CD_REG_FAT NUMBER(*),
  CD_STATUS NUMBER(1),
  CD_SETOR_ORIGEM NUMBER(*),
  CD_SETOR_DESTINO NUMBER(*),
  DT_ENVIO DATE,
  DT_RESPOSTA DATE,
  SN_REENVIADO VARCHAR2(1),
  SN_ARQUIVADO VARCHAR2(1),
  CONSTRAINT FK_NPTC_SETOR_ORIGEM FOREIGN KEY (CD_SETOR_ORIGEM) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_SETOR_DESTINO FOREIGN KEY (CD_SETOR_DESTINO) REFERENCES DBAMV.TB_SETOR (CD_SETOR),
  CONSTRAINT FK_NPTC_ANTEDIME FOREIGN KEY (CD_ATENDIMENTO) REFERENCES DBAMV.TB_ATENDIME (CD_ATENDIMENTO),
  CONSTRAINT FK_NPTC_REG_FAT FOREIGN KEY (CD_REG_FAT) REFERENCES DBAMV.REG_FAT (CD_REG_FAT)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_PROTOCOLO;

-- DOCUMENTO MANUAL

CREATE TABLE USRDBVAH.TB_NPTC_DOC_MANUAL
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  CD_CODIGO NUMBER(*),
  CD_TIPO NUMBER(2),
  NM_OBSERVACAO VARCHAR(50),
  CD_PRESTADOR NUMBER(*),
  DH_CRIACAO DATE,
  DH_IMPRESSAO DATE,
  CONSTRAINT FK_NPTC_DOC_MAN_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_DOC_MAN_PREST FOREIGN KEY (CD_PRESTADOR) REFERENCES DBAMV.PRESTADOR (CD_PRESTADOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_DOC_MANUAL;

-- HISTÓRICO

CREATE TABLE USRDBVAH.TB_NPTC_HISTORICO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  DT_ALTERACAO DATE,
  CD_STATUS NUMBER(1),
  CONSTRAINT FK_NPTC_HIST_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_HIST_USER FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_HISTORICO;

-- COMENTARIO

CREATE TABLE USRDBVAH.TB_NPTC_COMENTARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  DT_CRIACAO DATE,
  NM_COMENTARIO VARCHAR2(255),
  CONSTRAINT FK_NPTC_COMEN_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_COMEN_USER FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_COMENTARIO;

-- COMENTARIO

CREATE TABLE USRDBVAH.TB_NPTC_COMENTARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_PROTOCOLO NUMBER(*),
  ID_USER NUMBER(*),
  NM_COMENTARIO VARCHAR2(255),
  CONSTRAINT FK_NPTC_COMEN_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_COMEN_USER FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_NPTC_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_NPTC_HISTORICO;

-- TABELA RELACIONAMENTO PROTOCOLO PRESCRIÇÕES

CREATE TABLE USRDBVAH.TB_NPTC_PROT_PRESC
(
  ID_PROTOCOLO NUMBER(*),
  CD_PRE_MED NUMBER(*),
  CONSTRAINT TB_NPTC_PROT_PRESC_PK PRIMARY KEY (ID_PROTOCOLO, CD_PRE_MED),
  CONSTRAINT FK_NPTC_PROT_PRESC_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_PROT_PRESC_PRESC FOREIGN KEY (CD_PRE_MED) REFERENCES DBAMV.PRE_MED (CD_PRE_MED)
);

CREATE TABLE USRDBVAH.TB_NPTC_PROT_AVISO
(
  ID_PROTOCOLO NUMBER(*),
  CD_AVISO_CIRURGIA NUMBER(*),
  CONSTRAINT TB_NPTC_PROT_AVISO_PK PRIMARY KEY (ID_PROTOCOLO, CD_AVISO_CIRURGIA),
  CONSTRAINT FK_NPTC_PROT_AVISO_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_PROT_AVISO_AVISO FOREIGN KEY (CD_AVISO_CIRURGIA) REFERENCES DBAMV.TB_AVISO_CIRURGIA (CD_AVISO_CIRURGIA)
);

CREATE TABLE USRDBVAH.TB_NPTC_PROT_REG_DOC
(
  ID_PROTOCOLO NUMBER(*),
  CD_REGISTRO_DOCUMENTO NUMBER(*),
  CONSTRAINT TB_NPTC_PROT_REG_DOC_PK PRIMARY KEY (ID_PROTOCOLO, CD_REGISTRO_DOCUMENTO),
  CONSTRAINT FK_NPTC_PROT_REG_DOC_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES USRDBVAH.TB_NPTC_PROTOCOLO (ID),
  CONSTRAINT FK_NPTC_PROT_REG_DOC_REG_DOC FOREIGN KEY (CD_REGISTRO_DOCUMENTO) REFERENCES DBAMV.REGISTRO_DOCUMENTO (CD_REGISTRO_DOCUMENTO)
);